spring:
  config:
    activate:
      on-profile: test
  r2dbc:
    url: r2dbc:h2:mem:///test;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    name: sa
    password:
  liquibase:
    url: jdbc:h2:mem:///test;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    user: sa
    password:
    enabled: true